[package]
name = "tellyx"
version = "0.1.0"
description = "High-performance TellyX IPTV Player with Multi-Screen Quad View, WASM engine, and direct cross-origin stream loading."
authors = ["Armature.TN"]
edition = "2021"
license = "AGPL-3.0-or-later OR Commercial"

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
tauri = { version = "2.0.0", features = [] }
tauri-plugin-updater = "2.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
name = "tellyx_lib"
crate-type = ["staticlib", "cdylib", "rlib"]
